### PR TITLE
SCMOD-4407 : Update job-service release version

### PR DESCRIPTION
**Pull request by thilagasanthosh**
SCMOD-4407 : Update job-service release version.
@rado-straka  Please ignore the previous PR.

### CODE REVIEW

**Comment by thilagasanthosh** [comment]
@rado-straka  Plese ignore prev PR and review this.

**Comment by rado-straka** [comment]
@thilagasanthosh is there a build for this branch?

**Comment by rado-straka** [comment]
@thilagasanthosh PR is not assigned

**Comment by thilagasanthosh** [comment]
@rado-straka , I am not able to select Reviewers as I don't have permission to view reviewers list.

**Comment by thilagasanthosh** [comment]
@rado-straka ,PR is assigned now.

**Pull request closed without merging**
